---
- hosts: localhost
  tasks:
    - include_vars: secret.yml
    - name: Show the secret variables
      debug:
        msg:
          - "The DB password is {{ db_password }}”
          - “The API key is {{ api_key }}"

